---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
      - name: "registrysecret"
      containers:
      - name: basicapp
        command: ["java"]
        args: ["-jar", "/app/demo.jar", "$JAVA_OPT"]
{{ tuple "basicapp" . | include "werf_container_image" | indent 8 }}
        workingDir: /app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: JAVA_OPT
          value: "{{ pluck .Values.global.env .Values.app.java_opt | first | default .Values.app.java_opt._default }}"
        - name: POSTGRESQL_HOST
          value: {{ pluck .Values.global.env .Values.postgresql._postgresqlHost | first | default .Values.postgresql._postgresqlHost._default  | quote }}
        - name: POSTGRESQL_DATABASE
          value: {{ .Values.postgresql.postgresqlDatabase | quote }}
        - name: POSTGRESQL_LOGIN
          value: {{ .Values.postgresql.postgresqlUsername | quote }}
        - name: POSTGRESQL_PORT
          value: {{ .Values.postgresql.servicePort | quote }}
        - name: POSTGRESQL_PASSWORD
          value: {{ .Values.postgresql.postgresqlPassword | quote }}
{{ tuple "basicapp" . | include "werf_container_env" | indent 8 }}
